//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class interface_Cmodules {
  public static int factorial(int number) {
    int ret = interface_CmodulesPINVOKE.factorial(number);
    return ret;
  }

  public static void bubble_Sort(SWIGTYPE_p_int array_List, int length) {
    interface_CmodulesPINVOKE.bubble_Sort(SWIGTYPE_p_int.getCPtr(array_List), length);
  }

}
