/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class interface_CmodulesJNI {
  public final static native int factorial(int jarg1);
  public final static native void bubble_Sort(long jarg1, int jarg2);
}
