<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('interface_Cmodules')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_interface_Cmodules.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('interface_Cmodules.so')) return;
    } else {
      if (!dl('interface_Cmodules.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class interface_Cmodules {
	static function factorial($number) {
		return factorial($number);
	}

	static function bubble_Sort($array_List,$length) {
		bubble_Sort($array_List,$length);
	}
}

/* PHP Proxy Classes */

?>
