/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef PHP_INTERFACE_CMODULES_H
#define PHP_INTERFACE_CMODULES_H

extern zend_module_entry interface_Cmodules_module_entry;
#define phpext_interface_Cmodules_ptr &interface_Cmodules_module_entry

#ifdef PHP_WIN32
# define PHP_INTERFACE_CMODULES_API __declspec(dllexport)
#else
# define PHP_INTERFACE_CMODULES_API
#endif

ZEND_NAMED_FUNCTION(_wrap_factorial);
ZEND_NAMED_FUNCTION(_wrap_bubble_Sort);
PHP_MINIT_FUNCTION(interface_Cmodules);

#endif /* PHP_INTERFACE_CMODULES_H */
